version: '{build}'
image: Visual Studio 2017

branches:
  only:
  - master
  - develop

pull_requests:
  do_not_increment_build_number: true

build_script:
- ps: .\build\build.ps1

test_script:
- ps: .\build\test.ps1

artifacts:
- path: '**\*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: 6xI1jxoZzJ4pIWm4bIufAwdJGy467P+VdIll3/dAAGEpxgISXMIGwMWa77VT3yM9 
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
      branch: /^(master|develop)$/
